from google.cloud.bigquery import SchemaField 

tables = ['airport_codes', 'immigration_data', 'temperature_by_city', 'us_cities_demo']

airport_codes= [SchemaField('ident', 'STRING', 'NULLABLE', None, ())
,SchemaField('type', 'STRING', 'NULLABLE', None, ())
,SchemaField('name', 'STRING', 'NULLABLE', None, ())
,SchemaField('elevation_ft', 'INTEGER', 'NULLABLE', None, ())
,SchemaField('continent', 'STRING', 'NULLABLE', None, ())
,SchemaField('iso_country', 'STRING', 'NULLABLE', None, ())
,SchemaField('iso_region', 'STRING', 'NULLABLE', None, ())
,SchemaField('municipality', 'STRING', 'NULLABLE', None, ())
,SchemaField('gps_code', 'STRING', 'NULLABLE', None, ())
,SchemaField('iata_code', 'STRING', 'NULLABLE', None, ())
,SchemaField('local_code', 'STRING', 'NULLABLE', None, ())
,SchemaField('coordinates', 'STRING', 'NULLABLE', None, ())
,]

immigration_data= [SchemaField('cicid', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94yr', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94mon', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94cit', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94res', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94port', 'STRING', 'NULLABLE', None, ())
,SchemaField('arrdate', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94mode', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94addr', 'STRING', 'NULLABLE', None, ())
,SchemaField('depdate', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94bir', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('i94visa', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('count', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('dtadfile', 'STRING', 'NULLABLE', None, ())
,SchemaField('visapost', 'STRING', 'NULLABLE', None, ())
,SchemaField('occup', 'STRING', 'NULLABLE', None, ())
,SchemaField('entdepa', 'STRING', 'NULLABLE', None, ())
,SchemaField('entdepd', 'STRING', 'NULLABLE', None, ())
,SchemaField('entdepu', 'STRING', 'NULLABLE', None, ())
,SchemaField('matflag', 'STRING', 'NULLABLE', None, ())
,SchemaField('biryear', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('dtaddto', 'STRING', 'NULLABLE', None, ())
,SchemaField('gender', 'STRING', 'NULLABLE', None, ())
,SchemaField('insnum', 'STRING', 'NULLABLE', None, ())
,SchemaField('airline', 'STRING', 'NULLABLE', None, ())
,SchemaField('admnum', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('fltno', 'STRING', 'NULLABLE', None, ())
,SchemaField('visatype', 'STRING', 'NULLABLE', None, ())
,]

temperature_by_city= [SchemaField('dt', 'DATE', 'NULLABLE', None, ())
,SchemaField('AverageTemperature', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('AverageTemperatureUncertainty', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('City', 'STRING', 'NULLABLE', None, ())
,SchemaField('Country', 'STRING', 'NULLABLE', None, ())
,SchemaField('Latitude', 'STRING', 'NULLABLE', None, ())
,SchemaField('Longitude', 'STRING', 'NULLABLE', None, ())
,]

us_cities_demo= [SchemaField('City', 'STRING', 'NULLABLE', None, ())
,SchemaField('State', 'STRING', 'NULLABLE', None, ())
,SchemaField('Median_Age', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('Male_Population', 'INTEGER', 'NULLABLE', None, ())
,SchemaField('Female_Population', 'INTEGER', 'NULLABLE', None, ())
,SchemaField('Total_Population', 'INTEGER', 'NULLABLE', None, ())
,SchemaField('Number_of_Veterans', 'INTEGER', 'NULLABLE', None, ())
,SchemaField('Foreign_born', 'INTEGER', 'NULLABLE', None, ())
,SchemaField('Average_Household_Size', 'FLOAT', 'NULLABLE', None, ())
,SchemaField('State_Code', 'STRING', 'NULLABLE', None, ())
,SchemaField('Race', 'STRING', 'NULLABLE', None, ())
,SchemaField('Count', 'INTEGER', 'NULLABLE', None, ())
,]

